---
- name: Create GitLab Docker directory
  file:
    path: /opt/gitlab
    state: directory

- name: Create GitLab Docker Compose file
  copy:
    dest: /opt/gitlab/docker-compose.yml
    content: |
      version: '3.6'
      services:
        gitlab:
          image: gitlab/gitlab-ce:latest
          container_name: gitlab
          restart: always
          hostname: 'gitlab.local'
          environment:
            GITLAB_OMNIBUS_CONFIG: |
              external_url 'http://localhost:8929'
          ports:
            - '8929:8929'
            - '2222:22'
          volumes:
            - gitlab-config:/etc/gitlab
            - gitlab-logs:/var/log/gitlab
            - gitlab-data:/var/opt/gitlab

      volumes:
        gitlab-config:
        gitlab-logs:
        gitlab-data:

- name: Start GitLab container
  shell: docker-compose up -d
  args:
    chdir: /opt/gitlab
  become: true
